local addonName, ns = ...

ns.data = {
    bosses = {
        {
            id = "attumen",
            name = "Attumen the Huntsman",
            aliases = {"Attumen", "Midnight"},
            assignLabels = {"Tank plan", "Curse / dispel plan", "Charge positioning"},
            sections = {
                {"Raid Lead Summary", "Phase 1 starts on Midnight. At 95% Attumen joins, then the pair merge when either reaches 25%. Keep Attumen faced away and get the raid ready for charge after the mount-up."},
                {"Tank", "Be ready to snap Attumen the instant he spawns. Face him away from the raid to stop Shadow Cleave clipping melee. After the mount-up, keep the boss stable and leave one far target in a safe charge lane."},
                {"Healer", "Watch the Attumen pickup and the mounted phase closely. Knockdown can create tank spikes, and Intangible Presence can hurt hit chance for players near the boss if you are running dispels / curse cleanup."},
                {"DPS / Utility", "Stay out of frontals. Do not stand in the charge lane unless assigned as the safe far target. Melee should be ready for the merge timing so they do not get clipped by movement or cleave."},
            },
            announce = {
                "Attumen: start on Midnight, tank snap Attumen immediately at 95%.",
                "Face boss away at all times and keep melee out of the front.",
                "Mounted phase: safe charge lane only; everyone else stay tucked in.",
            },
        },
        {
            id = "moroes",
            name = "Moroes",
            aliases = {"Moroes"},
            assignLabels = {"Tank / second threat", "CC / kill order", "Garrote plan"},
            sections = {
                {"Raid Lead Summary", "This fight is won before the pull: assign CC, assign kill order, and make sure two tanks sit at the top of threat for Gouge. Moroes will Vanish into Garrote and enrages at 30%."},
                {"Tank", "Main tank on Moroes, off tank stays second on threat for Gouge. Pick up broken CC or dangerous guests if needed. Call a taunt or backup if Gouge happens at a bad time."},
                {"Healer", "Be ready for Vanish into Garrote damage and for the 30% enrage. Track who gets Garrote and call external healing or personal cooldowns on low-health targets."},
                {"DPS / Utility", "Stick to the assigned kill / CC order. Priest and paladin-style guests are usually the first priority because of Mana Burn, heals, and utility. Do not overtake tank threat during Gouge windows."},
            },
            announce = {
                "Moroes: follow assigned CC and kill order.",
                "Two tanks stay top threat for Gouge; do not rip during Gouge windows.",
                "Watch Vanish + Garrote and be ready for enrage at 30%.",
            },
            presets = {
                {
                    id = "default",
                    name = "Default mixed comp",
                    a1 = "MT = {MT1}, OT = {OT1} for Gouge, {DPS1} backup on loose guest",
                    a2 = "Moon = priest CC, Square = paladin CC, Skull = healer guest, X = priest/paladin guest, then boss",
                    a3 = "Priest + druid cover Garrote, healthstone/pot at low call, externals for enrage",
                    custom = "Before pull, repeat the guest marks out loud. If a CC breaks, call the mark first and the pickup second so the raid reacts cleanly.",
                },
                {
                    id = "paladin_heavy",
                    name = "Paladin-heavy control",
                    a1 = "MT = Moroes, OT = second threat, prot paladin cleans up broken CC",
                    a2 = "Repentance on healer guest, shackle on priest guest, skull -> X -> boss",
                    a3 = "Holy paladin on tank, priest + druid float Garrotes, bubble/bop emergencies on call",
                    custom = "Use blessing freedom / bop aggressively if a Garrote target is already low near enrage. Prot paladin should stand where loose guests path cleanly into consecrate.",
                },
                {
                    id = "lean_control",
                    name = "Low-CC / brute force",
                    a1 = "MT = Moroes, OT = second threat, all stuns/taunts ready for bad Gouge",
                    a2 = "Single hard CC on worst healer guest, then skull -> X -> square -> boss with hard focus swaps",
                    a3 = "Two assigned healers track Garrote targets, personals and stones early, push before the room gets messy",
                    custom = "If comp is weak on CC, make kill order and stop-cast discipline the priority. Call threat resets around Gouge more often because DPS tend to overpush this version.",
                },
            },
        },
        {
            id = "maiden",
            name = "Maiden of Virtue",
            aliases = {"Maiden", "Maiden of Virtue"},
            assignLabels = {"Spread pattern", "Cleanse / dispel", "Repentance recovery"},
            sections = {
                {"Raid Lead Summary", "Simple positioning fight. Spread around the room so Holy Wrath does not chain through the raid, and be ready to recover after Repentance."},
                {"Tank", "Keep Maiden centered and stable so the raid can stay spread. Avoid dragging her through the room and forcing healers into line-of-sight problems."},
                {"Healer", "Holy Fire targets need quick dispel / healing. Repentance can leave the tank briefly exposed, so pre-HoTs, shields, or a tremor / immunity plan help smooth the recovery."},
                {"DPS / Utility", "Keep your spread, do not stack the chain lightning-style Holy Wrath, and avoid drifting behind pillars where healers lose line of sight."},
            },
            announce = {
                "Maiden: spread around the room and keep line of sight clean.",
                "Do not chain Holy Wrath through the raid.",
                "Be ready for Repentance recovery and quick Holy Fire dispels.",
            },
        },
        {
            id = "opera",
            name = "Opera Event (Overview)",
            aliases = {"Opera", "Big Bad Wolf", "Julianne", "Romulo", "The Crone", "Wizard of Oz"},
            assignLabels = {"Weekly event call", "Special job 1", "Special job 2"},
            sections = {
                {"Raid Lead Summary", "Opera rotates weekly between Big Bad Wolf, Romulo and Julianne, and Wizard of Oz. Use this page as the quick scout overview, then swap to the matching Opera-specific page for exact assignments before pull."},
                {"Big Bad Wolf", "One player at a time becomes Red Riding Hood and must kite immediately without cutting through the raid. Everyone else gives the kiter room and helps keep fear recovery clean."},
                {"Romulo & Julianne", "Julianne heal interrupts and final-phase kill sync are the two raid-leader checks. Put your most reliable interrupter on Julianne and make a loud stop / finish call in the last phase."},
                {"Wizard of Oz", "Mark a kill order before pull. Dorothee and Tito are usually first concerns, Roar fear coverage matters, Strawman rewards fire damage, Tinhead should face away, and Crone is mainly a movement check."},
            },
            announce = {
                "Opera: confirm the weekly event before pull, then swap to the matching Opera page for assignments.",
                "BBW = kite lane. R&J = interrupt Julianne + sync final kill. Oz = follow the marked kill order.",
            },
        },
        {
            id = "opera_wolf",
            name = "Opera: Big Bad Wolf",
            aliases = {"Big Bad Wolf", "BBW", "Red Riding Hood"},
            assignLabels = {"Fear support", "Kite lane call", "Healer focus"},
            sections = {
                {"Raid Lead Summary", "This fight is mostly about one player kiting correctly while the rest of the raid stays out of the way. A bad kite path or panic crossover causes most wipes."},
                {"Raid Lead Calls", "Before the pull, mark the open lane the Hood target should run. Call that nobody crosses the room through the kite path. After Terrifying Howl, the raid resets quickly and gives the next target room."},
                {"Tank / Healer", "There is no traditional tanking structure here; success is healer attention and clean fear recovery. Healers should already know who is likely to be furthest and able to keep the Hood target alive while moving."},
                {"DPS / Utility", "Red Riding Hood target runs immediately and continuously. Everyone else keeps distance from the lane, uses fear help if assigned, and resumes damage once the path is safe again."},
            },
            announce = {
                "BBW: if you get Red Riding Hood, run immediately and keep the lane clean.",
                "Nobody cuts across the kite path. Fear support on call.",
                "Healers keep the current Hood target stable while moving.",
            },
            presets = {
                {
                    id = "wide_lane",
                    name = "Wide room kite lane",
                    a1 = "Fear Ward / Tremor on current group, backup freedom if panic crosses happen",
                    a2 = "Kite clockwise around the outside wall; nobody cuts middle unless called",
                    a3 = "Two mobile healers favor the current Hood target; third healer floats on fear recovery",
                    custom = "Mark the lane with voice before pull: hug outer wall, do not run through center. After each fear, everyone re-establishes the lane before resuming damage.",
                },
                {
                    id = "short_lane",
                    name = "Short lane / tight room",
                    a1 = "Shaman Tremor group set, priest on panic rescue",
                    a2 = "Hood target kites short side first, then cuts only on call once room is clear",
                    a3 = "Raid healer watches fear clumps, single-target healer tracks Hood target",
                    custom = "Use this if the room is crowded or your raid tends to overrun each other. Emphasize that the Hood target moves first and everyone else makes space.",
                },
            },
        },
        {
            id = "opera_rj",
            name = "Opera: Romulo & Julianne",
            aliases = {"Romulo and Julianne", "Romulo & Julianne", "Romulo", "Julianne", "R and J", "R&J"},
            assignLabels = {"Julianne interrupter", "Dispel / decurse", "Final kill sync"},
            sections = {
                {"Raid Lead Summary", "This encounter rewards assignment discipline more than raw output. Put one reliable interrupter on Julianne, keep dispels ready, and make a very clear final-phase stop-and-finish call so both bosses die together."},
                {"Raid Lead Calls", "Announce who owns Julianne heal interrupts before pull. Call every buff dispel. In the final phase, bring both bosses low together, stop damage if needed, then count down the finish so neither revives the other."},
                {"Tank", "Romulo should be faced away from the raid. Keep him steady so melee know exactly where the safe zone is and so the raid does not lose uptime during repositioning."},
                {"Healer / DPS", "Julianne cast control comes first. Save burst and cooldowns for the synchronized final kill instead of wasting them during a messy split-health phase."},
            },
            announce = {
                "R&J: assigned interrupter owns Julianne heals every cast.",
                "Dispels on call, Romulo faced away, and final phase is a synced kill.",
                "Do not tunnel one boss too low before the countdown.",
            },
            presets = {
                {
                    id = "one_kick",
                    name = "Single assigned interrupter",
                    a1 = "Rogue owns Julianne heals; mage CS is emergency backup only",
                    a2 = "Priest dispels buffs, druid decurse if needed",
                    a3 = "Bring both to ~10%, full stop, then 3-2-1 finish together",
                    custom = "Call every successful Julianne interrupt so the raid knows the cast is covered. In final phase, stop melee if one target drops faster than expected.",
                },
                {
                    id = "two_kick",
                    name = "Two-kick safety plan",
                    a1 = "Rogue first kick, shaman second, mage emergency CS if either is moving",
                    a2 = "Paladin/priest dispel team handles buffs immediately",
                    a3 = "Ranged slow damage once both are low; finish on leader countdown",
                    custom = "Use this for newer groups. The backup kicker should stand close enough to cover without chasing, and the raid leader should pre-call a stop if health bars desync.",
                },
            },
        },
        {
            id = "opera_oz",
            name = "Opera: Wizard of Oz",
            aliases = {"Wizard of Oz", "Oz", "Dorothee", "Roar", "Tinhead", "Strawman", "Crone"},
            assignLabels = {"Kill order", "Fear coverage", "Fire / offtank jobs"},
            sections = {
                {"Raid Lead Summary", "Oz is a marked-target discipline fight. The cleanest raids decide the exact kill order first, call fear help for Roar, and remind the raid which targets need special handling before the pull starts."},
                {"Recommended flow", "Typical order is Dorothee, Tito if he is causing problems, Roar, Strawman, Tinhead, then Crone. Adjust only if your comp or control tools strongly suggest a different path."},
                {"Special handling", "Fear help matters on Roar. Strawman is easier with fire damage because of stuns. Tinhead should be faced away if controlled by a tank or off-tank. On Crone, movement becomes the main leadership check because of Cyclones."},
                {"Raid Lead Calls", "Mark targets before pull and repeat the order once the fight starts. Warn melee before Tinhead angles get messy, then switch the whole raid mindset to movement and cyclone dodging on Crone."},
            },
            announce = {
                "Oz: follow the marked kill order exactly.",
                "Fear help on Roar, fire on Strawman, Tinhead faced away if assigned.",
                "Crone phase is movement first; dodge cyclones and finish cleanly.",
            },
            presets = {
                {
                    id = "standard",
                    name = "Standard kill order",
                    a1 = "Skull = Dorothee, X = Tito, Square = Roar, Triangle = Strawman, Moon = Tinhead",
                    a2 = "Fear Ward/Tremor on Roar phase, mage/lock fire swaps to Strawman",
                    a3 = "OT turns Tinhead away; whole raid spreads for Crone movement phase",
                    custom = "Repeat the marked order twice before pull. If Tito is not causing problems, call a calm swap back to Dorothee instead of letting the raid panic-target all over the stage.",
                },
                {
                    id = "tito_late",
                    name = "Dorothee first / Tito later",
                    a1 = "Skull = Dorothee, X = Roar, Square = Strawman, Moon = Tinhead; Tito only if healer pressure spikes",
                    a2 = "Fear coverage saved for Roar, fire users ready for Strawman stun windows",
                    a3 = "OT or plate wearer manages Tinhead facing; Crone = movement over greed",
                    custom = "Use this if your healers prefer less target churn. Call clearly whether Tito is being cleaved incidentally or intentionally focused so melee do not split damage by accident.",
                },
            },
        },
        {
            id = "curator",
            name = "The Curator",
            aliases = {"Curator", "The Curator"},
            assignLabels = {"Spark / flare control", "Evocation burn plan", "Hateful Bolt target"},
            sections = {
                {"Raid Lead Summary", "Controlled add cleanup into an Evocation burn. Assign flare kill focus, keep the Hateful Bolt target healthy, then push hard during Evocation."},
                {"Tank", "Keep Curator planted. If you use a dedicated Hateful Bolt soaker or off-tank structure, confirm it before pull so healers know who is taking the extra Arcane hit."},
                {"Healer", "Astral Flares create steady raid damage, and Hateful Bolt can spike the second target on threat. Save mana and cooldowns so the group can fully capitalize on Evocation."},
                {"DPS / Utility", "Swap quickly to Astral Flares and return to boss only when the current flare dies. During Evocation, commit cooldowns and maximize damage."},
            },
            announce = {
                "Curator: hard swap to every Astral Flare.",
                "Keep the Hateful Bolt target healthy.",
                "Full burn and cooldowns during Evocation.",
            },
        },
        {
            id = "illhoof",
            name = "Terestian Illhoof",
            aliases = {"Illhoof", "Terestian Illhoof", "Kil'rek"},
            assignLabels = {"Sacrifice break team", "Imp control", "Kil'rek timing"},
            sections = {
                {"Raid Lead Summary", "The fight is about instant Sacrifice breaks, controlled imp splash damage, and using Kil'rek deaths to make boss burn windows cleaner."},
                {"Tank", "Pick up Illhoof and be ready to grab Kil'rek whenever he respawns. Position the boss so the raid can cleave imps without chaos."},
                {"Healer", "Watch the Sacrifice target first. If chains stay up too long the target dies fast. Raid damage rises as imps pile up, so call for AoE control if the room gets messy."},
                {"DPS / Utility", "Start by killing Kil'rek for the Broken Pact debuff, then prioritize every Sacrifice chain instantly. Cleave / AoE imps as assigned, but never at the cost of a slow chain break."},
            },
            announce = {
                "Illhoof: chains die instantly every time.",
                "Kill Kil'rek on spawn windows for the debuff.",
                "Control imp count and do not let Sacrifice sit.",
            },
        },
        {
            id = "aran",
            name = "Shade of Aran",
            aliases = {"Aran", "Shade of Aran"},
            assignLabels = {"Interrupt order", "Elemental control", "Flame Wreath reminder"},
            sections = {
                {"Raid Lead Summary", "This is an awareness and interrupt fight. The two raid-killing calls are Flame Wreath and the pull-slow-explosion combo; both need calm voice calls."},
                {"Tank", "No conventional tank job here. Be ready to help collect Water Elementals at 40% if your group is short on crowd control."},
                {"Healer", "Spot-heal Dragon's Breath and missile targets, and expect extra chaos when Water Elementals spawn. The room-wide pull into Arcane Explosion is the largest predictable burst window."},
                {"DPS / Utility", "Interrupt Fireball and Frostbolt as a priority. If you get Flame Wreath, do not move. On magnetic pull, instantly run to the room edge. Control or kill Water Elementals at 40%."},
            },
            announce = {
                "Aran: do not move on Flame Wreath.",
                "Run to the wall immediately after the pull + slow combo starts.",
                "Follow interrupt order and control elementals at 40%.",
            },
        },
        {
            id = "netherspite",
            name = "Netherspite",
            aliases = {"Netherspite"},
            assignLabels = {"Red beam rotation", "Blue beam rotation", "Green beam / backup"},
            sections = {
                {"Raid Lead Summary", "This is the most assignment-heavy encounter in Kara. You win by pre-assigning beam rotations before the pull and calling swaps cleanly during portal and banish phases."},
                {"Tank", "Red beam soakers need a clean rotation or emergency backup. If the red beam misses, boss damage and survivability become unstable quickly."},
                {"Healer", "Green beam can be used for throughput and mana, but the boss must never be allowed to soak it. Plan which healer helps with green support and who covers portal soakers."},
                {"DPS / Utility", "Blue beam usually needs 2-3 rotating soakers. Watch your stacks, move for Void Zones, and spread or out-range Netherbreath during banish. Remember threat resets after banish ends."},
            },
            announce = {
                "Netherspite: follow beam assignments exactly.",
                "Red tank soaks, blue rotates, green can never reach the boss.",
                "Banish phase: spread or range the breath, then reset for threat wipe.",
            },
            presets = {
                {
                    id = "standard_2t",
                    name = "Standard 2-tank / 3-heal",
                    a1 = "Red: TankA -> TankB -> TankA (backup feral if portal path is bad)",
                    a2 = "Blue: Mage -> Hunter -> Warlock rotation, call swaps at 5-6 stacks",
                    a3 = "Green: Priest primary, Resto druid backup, never let boss touch green",
                    custom = "Portal phase: leader calls red / blue swaps loudly. Banish phase: spread for breath, reset threat mentally, and move back to portal anchors before the next set spawns.",
                },
                {
                    id = "safer_green",
                    name = "Safer green-healer plan",
                    a1 = "Red: Main tank only unless emergency call; OT ready if stacks or void zones force a swap",
                    a2 = "Blue: Two ranged rotate more aggressively at low stacks to keep movement simple",
                    a3 = "Green: Holy priest hard owns green, shaman backs portal soakers with chain heal",
                    custom = "Use this for groups that lose control when too many people rotate at once. Simpler swaps beat perfect DPS if execution has been shaky.",
                },
            },
        },
        {
            id = "chess",
            name = "Chess Event",
            aliases = {"Chess", "Chess Event", "Echo of Medivh"},
            assignLabels = {"King driver", "Healer piece coverage", "Backup callers"},
            sections = {
                {"Raid Lead Summary", "Not a conventional boss. Put your most confident callers on the king / major pieces, move forward with purpose, and focus on ending the match instead of over-microing every unit."},
                {"Tank / Caller", "Assign one primary shot-caller for movement and one backup in case a player gets knocked out of a piece or loses overview."},
                {"Raid", "Players controlling heal / support pieces should keep key frontliners active, but the raid should still play aggressively toward the enemy king instead of stalling the board."},
                {"Reminder", "If a player gets ejected, immediately re-enter a useful piece. Keep Medivh cheats from causing panic; recover and continue pressure."},
            },
            announce = {
                "Chess: follow the primary caller, keep pieces active, and push their king.",
                "If you get ejected, jump back into a useful piece immediately.",
            },
        },
        {
            id = "prince",
            name = "Prince Malchezaar",
            aliases = {"Prince", "Prince Malchezaar", "Malchezaar"},
            assignLabels = {"Infernal movement lane", "Enfeeble recovery", "Phase 3 healing"},
            sections = {
                {"Raid Lead Summary", "Prince is mostly positioning discipline. Keep the tank stable, give the raid clear infernal lanes, and call Enfeeble into Shadow Nova every time."},
                {"Tank", "Hold Prince where the raid has room to move as infernals land. Phase 2 hits harder because of Thrash, and Phase 3 can spike brutally if Amplify Damage lands on the tank."},
                {"Healer", "Enfeeble targets are at 1 HP and must be topped before Shadow Nova. In Phase 3, watch axe targets and any Amplify Damage on the tank or other players."},
                {"DPS / Utility", "After Enfeeble, get out of Shadow Nova range immediately. Respect infernal space all fight. In Phase 3, keep moving cleanly while the axes chase random players."},
            },
            announce = {
                "Prince: call every Enfeeble and get out for Shadow Nova.",
                "Respect infernal space and keep the movement lane clean.",
                "Phase 3: heavy healing on axe targets and any Amplify Damage tank.",
            },
            presets = {
                {
                    id = "safe_wall",
                    name = "Safe wall movement lane",
                    a1 = "Raid hugs wall lane clockwise; tank inches boss only when infernal blocks safe space",
                    a2 = "Priest + druid snap Enfeeble targets before every Shadow Nova",
                    a3 = "Paladin on tank, shaman/priest float on axe targets and Amplify Damage",
                    custom = "Call Enfeeble by voice every time even with BigWigs. The lane only works if people stop greed-casting and move immediately after the health drop.",
                },
                {
                    id = "wide_room",
                    name = "Wide-room conservative",
                    a1 = "Keep boss more central early, then drift toward open side only after bad infernals",
                    a2 = "Healers pre-HoT likely ranged clumps before Nova timing",
                    a3 = "Phase 3 externals reserved for Amplify tank or double-bad infernal + axes overlap",
                    custom = "Use this if your raid is better at reacting to space than holding a strict wall path. Still make one player call the next safe direction so the whole raid moves together.",
                },
            },
        },
        {
            id = "nightbane",
            name = "Nightbane",
            aliases = {"Nightbane"},
            assignLabels = {"Fear / totem plan", "Skeleton stack / AoE", "Air phase tank target"},
            sections = {
                {"Raid Lead Summary", "Nightbane rewards clean phase calls. Ground phase is a dragon positioning check; air phase is about stacking correctly, gathering skeletons, and stabilizing the Smoking Blast target."},
                {"Tank", "Keep head and tail away from the raid so melee can work from the side. During air phase, be ready to organize skeleton pickup as Rain of Bones lands."},
                {"Healer", "The Smoking Blast target takes consistent punishment in the air phase. Assign focused healing there, then rotate back to raid stabilization once the skeleton pack is under control."},
                {"DPS / Utility", "Stay out of front and tail, dodge Charred Earth, and stack tightly under Nightbane in air phases so Rain of Bones spawns skeletons together for AoE."},
            },
            announce = {
                "Nightbane: side melee only; stay out of head and tail.",
                "Air phase: stack under boss so skeletons spawn together.",
                "Focused healing on Smoking Blast target and fast AoE on skeletons.",
            },
            presets = {
                {
                    id = "tight_stack",
                    name = "Tight stack air phase",
                    a1 = "Tremor/Fear Ward group on melee stack; side-melee only on ground phase",
                    a2 = "Stack under boss marker, prot paladin/feral snaps skeletons, mage+lock AoE immediately",
                    a3 = "Holy priest + shaman hard swap to Smoking Blast target until skeletons are stable",
                    custom = "Best default for organized groups. Put a world marker or exact floor spot under the boss before summon so there is no argument about where the air-phase stack belongs.",
                },
                {
                    id = "safer_spread",
                    name = "Safer ranged reset",
                    a1 = "Fear help fixed by group before pull; melee still work from side only",
                    a2 = "Stack first for Rain of Bones, then ranged fan slightly once skeletons are gathered to reduce splash chaos",
                    a3 = "One healer locks Smoking Blast, one healer follows skeleton tank, third resets raid",
                    custom = "Use this if your group over-clumps too long after Rain of Bones. The critical point is still the initial stack so skeletons spawn together before the slight ranged fan-out.",
                },
            },
        },
    },
    trash = {
        {
            id = "stables",
            name = "Trash: Stables / Attumen Wing",
            aliases = {"Stables"},
            assignLabels = {"CC marks", "Fear plan", "Kill order"},
            sections = {
                {"What matters", "Spectral Chargers are dangerous because of Charge and Fear. Stable Hands bring Knockdown, armor reduction, and heals. This area is much easier if the raid stacks correctly and interrupts the healers."},
                {"Raid lead calls", "Mark Stable Hands for early kill or CC, call stack-behind on Chargers, and confirm Tremor / Fear Ward coverage before larger pulls."},
            },
            announce = {
                "Stable trash: stack behind chargers, stop fears, and kill / CC Stable Hands first.",
            },
        },
        {
            id = "ballroom",
            name = "Trash: Ballroom / Moroes Wing",
            aliases = {"Ballroom"},
            assignLabels = {"CC marks", "Mind control plan", "Tank danger"},
            sections = {
                {"What matters", "Retainers can mind control and strip buffs, Phantom Valets hit extremely hard, and Skeletal Waiters can leave the zero-armor Brittle Bones debuff on tanks."},
                {"Raid lead calls", "Pull cleanly into line-of-sight where possible, hard-focus Retainers, and watch for tanks carrying Brittle Bones into Valet damage."},
            },
            announce = {
                "Ballroom trash: Retainers die first, watch MCs, and respect Brittle Bones on tanks.",
            },
        },
        {
            id = "maidenhall",
            name = "Trash: Maiden Hallway",
            aliases = {"Maiden Hallway", "Holy Hallway"},
            assignLabels = {"Pull path", "Caster interrupts", "Patrol watch"},
            sections = {
                {"What matters", "This wing is lighter than ballroom trash, but sloppy pulls still punish weak interrupts and bad patrol timing."},
                {"Raid lead calls", "Pause for patrols, pull casters into clean line-of-sight positions, and keep the raid compact so nobody face-pulls ahead of the tank."},
            },
            announce = {
                "Maiden trash: slow and clean pulls, LOS casters, and wait for patrol timing.",
            },
        },
        {
            id = "operahall",
            name = "Trash: Opera Hall / Backstage",
            aliases = {"Opera Hall", "Backstage"},
            assignLabels = {"CC marks", "Patrol timing", "Do not overpull"},
            sections = {
                {"What matters", "This is one of the easiest places to lose a run to accidental overpulls. The area is packed, patrols overlap, and careless movement before or after Opera can snowball quickly."},
                {"Raid lead calls", "Set a strict stop point, mark patrol-sensitive pulls, and move only after the whole room is stable. Remind the raid not to drift forward during loot or roleplay."},
            },
            announce = {
                "Opera trash: hold position, respect patrols, and do not drift into extra packs.",
            },
        },
        {
            id = "curatorhall",
            name = "Trash: Menagerie / Curator Hall",
            aliases = {"Curator Hall", "Menagerie"},
            assignLabels = {"Safe room", "Pull-back point", "Reflect warning"},
            sections = {
                {"What matters", "The room before Curator punishes players who wander in early, and several mobs in this stretch hit hard or reflect specific damage types."},
                {"Raid lead calls", "Use a defined safe room / pull-back point, tell the raid not to step into Curator's room early, and warn DPS to stop into reflect if their health dips."},
            },
            announce = {
                "Curator hall: pull back to the safe room and stop attacking into reflects when called.",
            },
        },
        {
            id = "library",
            name = "Trash: Library / Shade Wing",
            aliases = {"Library", "Shade Wing"},
            assignLabels = {"Interrupt marks", "Sheep / banish", "Spacing"},
            sections = {
                {"What matters", "Caster-heavy pulls can get ugly if interrupts fail or the raid clumps too hard into splash and random damage."},
                {"Raid lead calls", "Assign kicks before the pull, use crowd control on extra casters, and keep ranged from stacking on top of each other without reason."},
            },
            announce = {
                "Library trash: kicks assigned, CC extras, and keep spacing clean.",
            },
        },
        {
            id = "netherspiteroom",
            name = "Trash: Netherspite Wing",
            aliases = {"Netherspite Room", "Nether Wing"},
            assignLabels = {"Mark priority", "Void zone watch", "Healer mana pace"},
            sections = {
                {"What matters", "The wing itself is manageable, but fatigue and sloppy movement make players eat unnecessary damage before one of Kara's most assignment-heavy bosses."},
                {"Raid lead calls", "Use marks even on simple pulls, avoid rushing between packs, and top everyone before engaging Netherspite so beam assignments start clean."},
            },
            announce = {
                "Netherspite wing: stay sharp, avoid lazy movement damage, and reset fully before boss.",
            },
        },
        {
            id = "brokenstair",
            name = "Trash: Broken Stair / Prince Ramp",
            aliases = {"Broken Stair", "Prince Ramp"},
            assignLabels = {"Tank spacing", "Cleave warning", "Stun / control"},
            sections = {
                {"What matters", "The final stair and ramp trash punishes tanks standing together and melee drifting into frontals or cleaves."},
                {"Raid lead calls", "Separate tanks when needed, keep the raid out of cleave angles, and do not rush the staircase where line of sight and pathing can become messy."},
            },
            announce = {
                "Prince ramp trash: tanks keep spacing, raid stays out of cleaves, and do not rush the stairs.",
            },
        },
        {
            id = "balcony",
            name = "Trash: Master's Terrace / Nightbane Setup",
            aliases = {"Balcony", "Nightbane Setup", "Master's Terrace"},
            assignLabels = {"Urn carrier", "Nightbane yes/no", "Pre-pull reset"},
            sections = {
                {"What matters", "Nightbane is optional, so confirm whether you are doing him before the raid moves out. If yes, make sure the Blackened Urn user is present and the raid is fully reset before the summon."},
                {"Raid lead calls", "Call for the urn carrier, mana break, soulstones / buffs, and exact stack point for the first air phase so the pull starts organized."},
            },
            announce = {
                "Nightbane setup: confirm urn carrier, full reset, then summon on call.",
            },
        },
    },
    utilities = {
        {
            id = "weeklyprep",
            name = "Utility: Weekly Prep",
            aliases = {"Weekly Prep", "Prep"},
            assignLabels = {"Consumables / summons", "Raid roles", "Optional boss check"},
            sections = {
                {"Checklist", "Confirm attuned players or door coverage, soulstones, healthstones, reagents, shards, raid markers, and whether Nightbane is on the plan for the night."},
                {"Role setup", "Pre-assign tanks, off-tanks, interrupt rotations, dispels, crowd control, and any special jobs before the first pull so you are not rebuilding structure at Moroes and Netherspite."},
            },
            announce = {
                "Weekly prep: confirm tanks, healers, interrupts, CC, and Nightbane plan before first pull.",
            },
        },
        {
            id = "raidflow",
            name = "Utility: Suggested Raid Flow",
            aliases = {"Raid Flow", "Route"},
            assignLabels = {"Break point", "Opera scout", "Nightbane slot"},
            sections = {
                {"Suggested order", "Typical order is Attumen, Moroes, Maiden, Opera, Curator, Illhoof, Shade, Netherspite, Chess, Prince, with Nightbane slotted in when your group is ready and has the summon."},
                {"Leader tips", "Use the easier early wings to identify weak interrupts, healer mana stability, and tank threat before committing to Moroes guests, Aran discipline, or Netherspite beam rotations."},
            },
            announce = {
                "Route check: early wings first, then deeper bosses; slot Nightbane only if the raid is ready.",
            },
        },
        {
            id = "moroespreset",
            name = "Utility: Moroes Assignment Sheet",
            aliases = {"Moroes Sheet", "Moroes Assignments", "Moroes Preset"},
            assignLabels = {"CC marks / players", "Kill order", "Garrote healing plan"},
            sections = {
                {"Suggested use", "Use this page before Moroes to write the exact guest marks, the kill order, and who is covering Garrote healing or removals. This keeps the real Moroes boss page cleaner for the actual pre-pull reminder."},
                {"Leader prompt", "Call the guests by mark and by class or mob type so nobody confuses the order. Confirm which tank is second threat for Gouge and who picks up loose guests if crowd control breaks."},
                {"Example structure", "Assignment 1: moon = priest, square = paladin, triangle = warrior. Assignment 2: kill order skull -> X -> boss. Assignment 3: Garrote healers = priest + druid, stone / pot on low calls."},
            },
            announce = {
                "Moroes sheet: confirm guest marks, kill order, and Garrote coverage before pull.",
            },
            presets = {
                {
                    id = "sheet_default",
                    name = "Default CC sheet",
                    a1 = "Moon priest = Shackle, Square paladin = Repentance/Trap, Triangle warrior = OT backup",
                    a2 = "Skull healer guest -> X priest/paladin guest -> triangle -> boss",
                    a3 = "Garrote coverage = Priest + Druid; healthstones early on low targets",
                    custom = "Swap these marks to match the actual guest set, then use the boss page for the quick live reminder once the plan is settled.",
                },
                {
                    id = "sheet_burst",
                    name = "Low-CC burst sheet",
                    a1 = "Single hard CC on worst caster, all other control is stuns/taunts on break",
                    a2 = "Skull -> X -> Moon -> boss with all DPS hard swapping on leader call",
                    a3 = "Extra healer pre-assigned to Garrotes before enrage push",
                    custom = "Useful when your comp changes week to week and you cannot rely on multiple long CCs. Keep the note box updated with the actual guest names you saw at the pull.",
                },
            },
        },
        {
            id = "netherspitebeams",
            name = "Utility: Netherspite Beam Rotation",
            aliases = {"Beam Rotation", "Netherspite Beams", "Beam Sheet"},
            assignLabels = {"Red beam order", "Blue beam order", "Green beam / backups"},
            sections = {
                {"Suggested use", "Fill this page with exact player names before the pull. This is meant to be your quick reference so you can announce the beam assignments without rewriting them every week."},
                {"Leader prompt", "Say the first soaker and the backup for every beam. Make sure everyone knows who takes over if a portal soaker dies, gets banished poorly, or has to move for a void zone."},
                {"Example structure", "Assignment 1: TankA -> TankB -> TankA. Assignment 2: Mage -> Hunter -> Warlock. Assignment 3: Priest on green, Resto druid backup, boss never touches green."},
            },
            announce = {
                "Beam sheet: red, blue, and green rotations are set; follow them exactly.",
            },
            presets = {
                {
                    id = "beam_standard",
                    name = "Standard beam sheet",
                    a1 = "Red = {MT1} -> {OT1} -> {MT1}",
                    a2 = "Blue = {DPS1} -> {DPS2} -> {DPS3}",
                    a3 = "Green = {HEALER1} primary, {HEALER2} backup",
                    custom = "Replace placeholders with player names before pull. If one soaker dies, call the backup by name immediately instead of saying 'someone take it'.",
                },
                {
                    id = "beam_simple",
                    name = "Simple backup sheet",
                    a1 = "Red = MT only, OT emergency backup",
                    a2 = "Blue = Ranged1 -> Ranged2 only",
                    a3 = "Green = Healer1, Healer2 emergency",
                    custom = "For newer groups, fewer swaps can be cleaner. Just make sure the shorter rotation will not overstack anyone before portals end.",
                },
            },
        },
        {
            id = "nightbaneair",
            name = "Utility: Nightbane Air Phase",
            aliases = {"Nightbane Air", "Air Phase", "Nightbane Sheet"},
            assignLabels = {"Stack point", "Skeleton pickup / AoE", "Smoking Blast healers"},
            sections = {
                {"Suggested use", "This page is for the one part of Nightbane that usually needs the most explanation: where to stack in air phase, who gathers the skeletons, and which healers stabilize the Smoking Blast target."},
                {"Leader prompt", "Before summon, point to the exact stack location under the boss and say it in voice. Confirm which tank or snap-threat player grabs the skeleton pack and who swaps hardest onto the blast target."},
                {"Example structure", "Assignment 1: stack under boss marker. Assignment 2: paladin gathers + mage / warlock AoE. Assignment 3: holy priest + shaman on Smoking Blast target until skeletons are stable."},
            },
            announce = {
                "Nightbane air phase: stack point, skeleton pickup, and Smoking Blast healing are assigned.",
            },
            presets = {
                {
                    id = "air_standard",
                    name = "Standard air phase",
                    a1 = "Stack point = under boss marker / left of summon bone",
                    a2 = "Skeleton pickup = {OT1}, AoE = {DPS1} + {DPS2}",
                    a3 = "Smoking Blast = {HEALER1} + {HEALER2}",
                    custom = "This is the clean default. Keep the stack point text updated to match the actual mark you use in your guild.",
                },
                {
                    id = "air_no_pally",
                    name = "No prot paladin air phase",
                    a1 = "Stack point = under boss, then slight ranged spread once adds are gripped",
                    a2 = "Skeleton pickup = feral/warrior with hunter misdirect if available, AoE = lock seed + mage",
                    a3 = "Smoking Blast = priest single-target, druid HoTs, shaman stabilizes raid",
                    custom = "Use this if your weekly Kara does not have a prot paladin. The pickup player needs a louder pre-call because the skeleton gather is less automatic.",
                },
            },
        },
        {
            id = "healercoverage",
            name = "Utility: Healer Coverage",
            aliases = {"Healer Sheet", "Healer Coverage", "Healing Assignments"},
            assignLabels = {"Tank healer(s)", "Raid healer(s)", "Special assignment"},
            sections = {
                {"Suggested use", "Use this as your generic healing sheet for bosses where you want one-click reminders without changing the encounter note itself. It works especially well for Prince, Nightbane, Moroes, and Curator."},
                {"Leader prompt", "Keep it simple: who owns the tank, who floats on raid, and who handles the special danger target such as Enfeeble recovery, Smoking Blast, Hateful Bolt, or Garrote players."},
                {"Example structure", "Assignment 1: paladin on tank. Assignment 2: priest + druid on raid. Assignment 3: shaman floats to special targets / emergency dispels."},
            },
            announce = {
                "Healing sheet: tank, raid, and special-target healing assignments are set.",
            },
            presets = {
                {
                    id = "three_heal",
                    name = "Standard 2-heal split",
                    a1 = "{HEALER1} on tank focus",
                    a2 = "{HEALER2} on raid with pre-HoTs and fast Enfeeble / Garrote recovery",
                    a3 = "{DPS6} backup utility on dispels / stones / emergency support",
                    custom = "Good generic Kara split for Prince, Curator, and Nightbane when you run 2 healers and a utility-heavy DPS core. Replace the roles with actual names if you want to announce it directly.",
                },
                {
                    id = "two_heal",
                    name = "Lean 2-heal split",
                    a1 = "Healer1 hard owns tank",
                    a2 = "Healer2 owns raid and light special coverage",
                    a3 = "Hybrids cover emergency support / cleanse / personals",
                    custom = "Only use this on easier farm pulls. The special-assignment slot is where you should note exactly which hybrid is helping if things go wrong.",
                },
            },
        },
        {
            id = "kickmatrix",
            name = "Utility: Interrupt / Dispel Matrix",
            aliases = {"Kick Matrix", "Interrupts", "Dispel Matrix"},
            assignLabels = {"Primary kicks", "Backup kicks", "Dispel / cleanse"},
            sections = {
                {"Suggested use", "Use this page for trash wings or boss fights where one missed interrupt causes chaos. It gives you a place to save the weekly names without editing the encounter page itself."},
                {"Leader prompt", "Call a primary and backup kick for every dangerous cast. If dispels matter, name the dispeller too instead of assuming the raid will sort it out during the pull."},
                {"Example structure", "Assignment 1: rogue then shaman. Assignment 2: warrior then mage CS on backup. Assignment 3: paladin cleanse, priest dispel magic, druid decurse."},
            },
            announce = {
                "Kick matrix: primary kicks, backups, and dispels are assigned.",
            },
            presets = {
                {
                    id = "standard_kicks",
                    name = "Standard kick matrix",
                    a1 = "Primary = {KICK1} on skull, {KICK2} on X",
                    a2 = "Backup = {DPS1} on drift casts, {DPS2} emergency backup",
                    a3 = "Dispels = {DISPEL1} primary, {DISPEL2} backup",
                    custom = "Use this for trash wings and for Romulo & Julianne if you want a separate reminder page. Replace the generic roles with names when the roster changes.",
                },
                {
                    id = "caster_heavy",
                    name = "Caster-heavy backup plan",
                    a1 = "Primary = shaman/rogue on dangerous healer casts only",
                    a2 = "Backup = mage CS and warlock spell lock on misses",
                    a3 = "Dispels = priest first, paladin second",
                    custom = "Helpful when melee attendance is thin. Call out which casts are truly mandatory so casters do not waste their utility on low-value interrupts.",
                },
            },
        },
        {
            id = "fastcalls",
            name = "Utility: Fast Reminder Calls",
            aliases = {"Fast Calls", "Reminders"},
            assignLabels = {"Callout 1", "Callout 2", "Callout 3"},
            sections = {
                {"Useful universal calls", "Melee out of frontals. Hold for patrol. Stop on threat. Kick order now. Spread. Collapse. Do not move. Reset and drink. Marked target dies first."},
                {"Use", "Save your team-specific short calls in the custom notes box for this utility entry and announce them before recurring trouble pulls."},
            },
            announce = {
                "Fast calls loaded: use your saved short reminders here for recurring mistakes.",
            },
        },
    },
}
